# Generated by Django 5.1rc1 on 2024-10-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimportprovince',
            options={'ordering': ('province_code', 'province_name'), 'verbose_name': 'Province data imported from GitHub', 'verbose_name_plural': 'Province data imported from GitHub'},
        ),
        migrations.RemoveField(
            model_name='dataimportprovince',
            name='codice_provincia',
        ),
        migrations.RemoveField(
            model_name='dataimportprovince',
            name='codice_regione',
        ),
        migrations.RemoveField(
            model_name='dataimportprovince',
            name='denominazione_provincia',
        ),
        migrations.RemoveField(
            model_name='dataimportprovince',
            name='denominazione_regione',
        ),
        migrations.RemoveField(
            model_name='dataimportprovince',
            name='sigla_provincia',
        ),
        migrations.RemoveField(
            model_name='dataimportprovince',
            name='stato',
        ),
        migrations.RemoveField(
            model_name='dataimportprovince',
            name='totale_casi',
        ),
        migrations.AddField(
            model_name='dataimportprovince',
            name='province_abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province abbreviation'),
        ),
        migrations.AddField(
            model_name='dataimportprovince',
            name='province_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Province code'),
        ),
        migrations.AddField(
            model_name='dataimportprovince',
            name='province_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province name'),
        ),
        migrations.AddField(
            model_name='dataimportprovince',
            name='region_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Region code'),
        ),
        migrations.AddField(
            model_name='dataimportprovince',
            name='region_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region name'),
        ),
        migrations.AddField(
            model_name='dataimportprovince',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='dataimportprovince',
            name='total_cases',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total of cases'),
        ),
        migrations.AlterField(
            model_name='dataimportprovince',
            name='codice_nuts_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuts code 1'),
        ),
        migrations.AlterField(
            model_name='dataimportprovince',
            name='codice_nuts_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuts code 2'),
        ),
        migrations.AlterField(
            model_name='dataimportprovince',
            name='codice_nuts_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuts code 3'),
        ),
    ]
